// <auto-generated />
#nullable enable

namespace Equatable.Attributes
{
    /// <summary>
    /// Marks a class, record or structure for source generation of equality members.
    /// </summary>
    /// <remarks>
    /// <para>
    /// For classes and structures, the generator implements <see cref="global::System.IEquatable{T}"/> and generates
    /// strongly typed and object-based <c>Equals</c> methods, <c>GetHashCode</c>, and the <c>==</c> and <c>!=</c> operators.
    /// </para>
    /// <para>
    /// For records, the generator provides the strongly typed <c>Equals</c> method and <c>GetHashCode</c>; the compiler
    /// provides the remaining equality members.
    /// </para>
    /// </remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.Conditional("EQUATABLE_GENERATOR")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct)]
    internal class EquatableAttribute : System.Attribute;

    /// <summary>
    /// Specifies that dictionary contents are used when comparing the attributed member and computing its hash code.
    /// </summary>
    /// <remarks>
    /// Dictionaries are equal when they are the same instance, or when they have the same number of entries and every
    /// key in the first dictionary resolves to an equal value in the second. Values are compared using
    /// <see cref="global::System.Collections.Generic.EqualityComparer{T}.Default"/>. Hash codes are independent of entry order.
    /// </remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.Conditional("EQUATABLE_GENERATOR")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field)]
    internal class DictionaryEqualityAttribute : global::System.Attribute;

    /// <summary>
    /// Specifies that set equality semantics are used when comparing the attributed member and computing its hash code.
    /// </summary>
    /// <remarks>
    /// Sets are equal when they are the same instance, or when they contain the same elements regardless of order.
    /// <see cref="global::System.Collections.Generic.ISet{T}.SetEquals(global::System.Collections.Generic.IEnumerable{T})"/>
    /// is used when either value implements <see cref="global::System.Collections.Generic.ISet{T}"/>; otherwise, the
    /// first sequence is converted to a <see cref="global::System.Collections.Generic.HashSet{T}"/> using the default
    /// element comparer. Hash codes are independent of element order.
    /// </remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.Conditional("EQUATABLE_GENERATOR")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field)]
    internal class HashSetEqualityAttribute : global::System.Attribute;

    /// <summary>
    /// Specifies that sequence equality semantics are used when comparing the attributed member and computing its hash code.
    /// </summary>
    /// <remarks>
    /// Sequences are equal when they are the same instance, or when they contain equal elements in the same order.
    /// Elements are compared using <see cref="global::System.Collections.Generic.EqualityComparer{T}.Default"/>.
    /// Sequence order contributes to the generated hash code.
    /// </remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.Conditional("EQUATABLE_GENERATOR")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field)]
    internal class SequenceEqualityAttribute : global::System.Attribute;

    /// <summary>
    /// Specifies that reference identity is used when comparing the attributed member and computing its hash code.
    /// </summary>
    /// <remarks>
    /// Equality is computed with <see cref="global::System.Object.ReferenceEquals(object, object)"/>, and the hash code
    /// is computed with <see cref="global::System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(object)"/>.
    /// </remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.Conditional("EQUATABLE_GENERATOR")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field)]
    internal class ReferenceEqualityAttribute : global::System.Attribute;

    /// <summary>
    /// Specifies the type of comparison to use when comparing the attributed string member and computing its hash code.
    /// </summary>
    /// <remarks>
    /// The <see cref="global::System.StringComparer"/> corresponding to <paramref name="comparisonType"/> is used for
    /// both equality and hash code generation.
    /// </remarks>
    /// <param name="comparisonType">The <see cref="global::System.StringComparison"/> value that defines the comparison rules.</param>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.Conditional("EQUATABLE_GENERATOR")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field)]
    internal class StringEqualityAttribute(global::System.StringComparison comparisonType) : global::System.Attribute
    {
        /// <summary>
        /// Gets the comparison rules to use.
        /// </summary>
        internal global::System.StringComparison ComparisonType { get; } = comparisonType;
    }

    /// <summary>
    /// Specifies a custom equality comparer to use for the attributed member.
    /// </summary>
    /// <remarks>
    /// The comparer is obtained from the named static property on <paramref name="equalityType"/>. Its
    /// <see cref="global::System.Collections.Generic.IEqualityComparer{T}.Equals(T, T)"/> and
    /// <see cref="global::System.Collections.Generic.IEqualityComparer{T}.GetHashCode(T)"/> methods are used by the
    /// generated equality members.
    /// </remarks>
    /// <param name="equalityType">The type that provides the equality comparer.</param>
    /// <param name="instanceName">The name of the static property that provides the comparer instance.</param>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.Conditional("EQUATABLE_GENERATOR")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field)]
    internal class EqualityComparerAttribute(global::System.Type equalityType, global::System.String instanceName = "Default") : global::System.Attribute
    {
        /// <summary>
        /// Gets the type that provides the equality comparer.
        /// </summary>
        public global::System.Type EqualityType { get; } = equalityType;

        /// <summary>
        /// Gets the name of the static property that provides the comparer instance.
        /// </summary>
        public global::System.String InstanceName { get; } = instanceName ?? "Default";
    }

    /// <summary>
    /// Excludes the attributed member from generated equality and hash code operations.
    /// </summary>
    /// <remarks>
    /// The attributed field or property does not contribute to generated equality comparisons or hash codes.
    /// </remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.Diagnostics.Conditional("EQUATABLE_GENERATOR")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field)]
    internal class IgnoreEqualityAttribute : global::System.Attribute;
}
