// <auto-generated />
#nullable enable

namespace Equatable
{
    /// <summary>
    /// Provides helper methods for equality and hash code calculations for common collection types.
    /// </summary>
    /// <remarks>
    /// Hash code methods use the classic rolling prime hash combiner pattern (the same style older Visual Studio generators used)
    /// to provide the best compatibility with legacy frameworks.
    /// </remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class Comparer
    {
        /// <summary>The seed value for hash code calculations.</summary>
        internal const int HashSeed = -1758092530;

        /// <summary>The multiplier value for hash code calculations.</summary>
        internal const int HashMultiplier = -1521134295;


        /// <summary>
        /// Compares two sequences for equality using the default comparer for <typeparamref name="T"/>.
        /// </summary>
        /// <param name="left">The first sequence to compare.</param>
        /// <param name="right">The second sequence to compare.</param>
        /// <returns><see langword="true"/> if both sequences are equal; otherwise, <see langword="false"/>.</returns>
        internal static bool SequenceEquals<T>(global::System.Collections.Generic.IEnumerable<T>? left, global::System.Collections.Generic.IEnumerable<T>? right)
        {
            if (global::System.Object.ReferenceEquals(left, right))
                return true;

            if (left is null || right is null)
                return false;

            var valueComparer = global::System.Collections.Generic.EqualityComparer<T>.Default;
            return global::System.Linq.Enumerable.SequenceEqual(left, right, valueComparer);
        }

        /// <summary>
        /// Compares two dictionaries for key and value equality.
        /// </summary>
        /// <param name="left">The first dictionary to compare.</param>
        /// <param name="right">The second dictionary to compare.</param>
        /// <returns><see langword="true"/> if both dictionaries contain the same keys and values; otherwise, <see langword="false"/>.</returns>
        internal static bool DictionaryEquals<TKey, TValue>(global::System.Collections.Generic.IDictionary<TKey, TValue>? left, global::System.Collections.Generic.IDictionary<TKey, TValue>? right)
        {
            if (global::System.Object.ReferenceEquals(left, right))
                return true;

            if (left is null || right is null)
                return false;

            if (left.Count != right.Count)
                return false;

            var valueComparer = global::System.Collections.Generic.EqualityComparer<TValue>.Default;
            foreach (var pair in left)
            {
                if (!right.TryGetValue(pair.Key, out var value))
                    return false;

                if (!valueComparer.Equals(pair.Value, value))
                    return false;
            }

            return true;
        }

        /// <summary>
        /// Compares two sets for equality without considering element order.
        /// </summary>
        /// <param name="left">The first set or sequence to compare.</param>
        /// <param name="right">The second set or sequence to compare.</param>
        /// <returns><see langword="true"/> if both sets contain the same elements; otherwise, <see langword="false"/>.</returns>
        internal static bool HashSetEquals<T>(global::System.Collections.Generic.IEnumerable<T>? left, global::System.Collections.Generic.IEnumerable<T>? right)
        {
            if (global::System.Object.ReferenceEquals(left, right))
                return true;

            if (left is null || right is null)
                return false;

            if (left is global::System.Collections.Generic.ISet<T> leftSet)
                return leftSet.SetEquals(right);

            if (right is global::System.Collections.Generic.ISet<T> rightSet)
                return rightSet.SetEquals(left);

            var valueComparer = global::System.Collections.Generic.EqualityComparer<T>.Default;
            var hashSet = new global::System.Collections.Generic.HashSet<T>(left, valueComparer);

            return hashSet.SetEquals(right);
        }


        /// <summary>
        /// Computes a hash code for a sequence using the default comparer for <typeparamref name="T"/>.
        /// </summary>
        /// <param name="items">The sequence to hash.</param>
        /// <returns>A hash code for the sequence, or <c>0</c> when <paramref name="items"/> is <see langword="null"/>.</returns>
        internal static int SequenceHashCode<T>(global::System.Collections.Generic.IEnumerable<T>? items)
        {
            if (items is null)
                return 0;

            int hashCode = HashSeed;

            var valueComparer = global::System.Collections.Generic.EqualityComparer<T>.Default;
            foreach (var item in items)
                hashCode = (hashCode * HashMultiplier) + (item is null ? 0 : valueComparer.GetHashCode(item));

            return hashCode;
        }

        /// <summary>
        /// Computes an order-independent hash code for a dictionary.
        /// </summary>
        /// <param name="items">The dictionary to hash.</param>
        /// <returns>A hash code for the dictionary, or <c>0</c> when <paramref name="items"/> is <see langword="null"/>.</returns>
        internal static int DictionaryHashCode<TKey, TValue>(global::System.Collections.Generic.IDictionary<TKey, TValue>? items)
        {
            if (items is null)
                return 0;

            int hashCode = HashSeed;

            var keyComparer = global::System.Collections.Generic.EqualityComparer<TKey>.Default;
            var valueComparer = global::System.Collections.Generic.EqualityComparer<TValue>.Default;

            // XOR is commutative and associative so order of iteration doesn't matter
            foreach (var item in items)
            {
                int keyHash = item.Key is null ? 0 : keyComparer.GetHashCode(item.Key);
                int valueHash = item.Value is null ? 0 : valueComparer.GetHashCode(item.Value);

                hashCode ^= keyHash ^ valueHash;
            }

            return hashCode;
        }

        /// <summary>
        /// Computes an order-independent hash code for a set.
        /// </summary>
        /// <param name="items">The set or sequence to hash.</param>
        /// <returns>A hash code for the set, or <c>0</c> when <paramref name="items"/> is <see langword="null"/>.</returns>
        internal static int HashSetHashCode<T>(global::System.Collections.Generic.IEnumerable<T>? items)
        {
            if (items is null)
                return 0;

            int hashCode = HashSeed;

            var valueComparer = global::System.Collections.Generic.EqualityComparer<T>.Default;

            // XOR is commutative and associative so order of iteration doesn't matter
            foreach (var item in items)
                hashCode ^= item is null ? 0 : valueComparer.GetHashCode(item);

            return hashCode;
        }

        /// <summary>
        /// Computes a stable hash code for a nullable Boolean value.
        /// </summary>
        /// <param name="value">The nullable Boolean value to hash.</param>
        /// <returns><c>-1</c> for <see langword="null"/>, <c>0</c> for <see langword="false"/>, and <c>1</c> for <see langword="true"/>.</returns>
        internal static int NullableBoolHashCode(bool? value)
        {
            return value switch
            {
                null => -1,
                false => 0,
                true => 1
            };
        }
    }
}
