// <auto-generated />
#nullable enable

namespace Equatable
{
    /// <summary>
    /// Provides helper methods for equality and hash code calculations for common collection types.
    /// </summary>
    /// <remarks>
    /// Hash code methods use the classic rolling prime hash combiner pattern (the same style older Visual Studio generators used)
    /// to provide the best compatibility with legacy frameworks.
    /// </remarks>
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    internal static class Comparer
    {
        /// <summary>The seed value for hash code calculations.</summary>
        internal const int HashSeed = -1758092530;

        /// <summary>The multiplier value for hash code calculations.</summary>
        internal const int Multiplier = -1521134295;

        /// <summary>The hash code used for null values so they don't collide with default values like <see langword="false"/> or zero.</summary>
        internal const int NullValue = -1;


        /// <summary>
        /// Compares two sequences for equality using the default comparer for <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T">The type of the elements in the sequences.</typeparam>
        /// <param name="left">The first sequence to compare.</param>
        /// <param name="right">The second sequence to compare.</param>
        /// <returns><see langword="true"/> if both sequences are equal; otherwise, <see langword="false"/>.</returns>
        /// <remarks>
        /// Elements are compared in order. Two <see langword="null"/> sequences are considered equal, while a single
        /// <see langword="null"/> sequence is not. When both sequences expose a count, differing counts short circuit
        /// the comparison without enumerating either sequence.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        internal static bool SequenceEquals<T>(global::System.Collections.Generic.IEnumerable<T>? left, global::System.Collections.Generic.IEnumerable<T>? right)
        {
            if (global::System.Object.ReferenceEquals(left, right))
                return true;

            if (left is null || right is null)
                return false;

            // only compare counts when both sequences expose one
            if (TryGetCount(left, out var leftCount) && TryGetCount(right, out var rightCount) && leftCount != rightCount)
                return false;

            var valueComparer = global::System.Collections.Generic.EqualityComparer<T>.Default;
            return global::System.Linq.Enumerable.SequenceEqual(left, right, valueComparer);
        }

        /// <summary>
        /// Compares two dictionaries for key and value equality.
        /// </summary>
        /// <typeparam name="TKey">The type of the keys in the dictionaries.</typeparam>
        /// <typeparam name="TValue">The type of the values in the dictionaries.</typeparam>
        /// <param name="left">The first dictionary to compare.</param>
        /// <param name="right">The second dictionary to compare.</param>
        /// <returns><see langword="true"/> if both dictionaries contain the same keys and values; otherwise, <see langword="false"/>.</returns>
        /// <remarks>
        /// The comparison is order independent. Two <see langword="null"/> dictionaries are considered equal, while a
        /// single <see langword="null"/> dictionary is not. Differing counts short circuit the comparison. Keys are
        /// matched using the comparer of <paramref name="right"/> and values use the default comparer for
        /// <typeparamref name="TValue"/>.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        internal static bool DictionaryEquals<TKey, TValue>(global::System.Collections.Generic.IDictionary<TKey, TValue>? left, global::System.Collections.Generic.IDictionary<TKey, TValue>? right)
        {
            if (global::System.Object.ReferenceEquals(left, right))
                return true;

            if (left is null || right is null)
                return false;

            if (left.Count != right.Count)
                return false;

            var valueComparer = global::System.Collections.Generic.EqualityComparer<TValue>.Default;
            foreach (var pair in left)
            {
                if (!right.TryGetValue(pair.Key, out var value))
                    return false;

                if (!valueComparer.Equals(pair.Value, value))
                    return false;
            }

            return true;
        }

        /// <summary>
        /// Compares two sets for equality without considering element order.
        /// </summary>
        /// <typeparam name="T">The type of the elements in the sets.</typeparam>
        /// <param name="left">The first set or sequence to compare.</param>
        /// <param name="right">The second set or sequence to compare.</param>
        /// <returns><see langword="true"/> if both sets contain the same elements; otherwise, <see langword="false"/>.</returns>
        /// <remarks>
        /// Two <see langword="null"/> sequences are considered equal, while a single <see langword="null"/> sequence is not.
        /// When both sequences expose a count, differing counts short circuit the comparison. If either sequence implements
        /// <see cref="global::System.Collections.Generic.ISet{T}"/> its <c>SetEquals</c> method is used directly; otherwise the
        /// elements are copied into a temporary <see cref="global::System.Collections.Generic.HashSet{T}"/>.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        internal static bool HashSetEquals<T>(global::System.Collections.Generic.IEnumerable<T>? left, global::System.Collections.Generic.IEnumerable<T>? right)
        {
            if (global::System.Object.ReferenceEquals(left, right))
                return true;

            if (left is null || right is null)
                return false;

            // only compare counts when both sequences expose one
            if (TryGetCount(left, out var leftCount) && TryGetCount(right, out var rightCount) && leftCount != rightCount)
                return false;

            if (left is global::System.Collections.Generic.ISet<T> leftSet)
                return leftSet.SetEquals(right);

            if (right is global::System.Collections.Generic.ISet<T> rightSet)
                return rightSet.SetEquals(left);

            var valueComparer = global::System.Collections.Generic.EqualityComparer<T>.Default;
            var hashSet = new global::System.Collections.Generic.HashSet<T>(left, valueComparer);

            return hashSet.SetEquals(right);
        }

        /// <summary>
        /// Compares two strings for equality using the specified <see cref="global::System.StringComparison"/>.
        /// </summary>
        /// <param name="left">The first string to compare.</param>
        /// <param name="right">The second string to compare.</param>
        /// <param name="comparison">
        /// The comparison rules to use. When <see langword="null"/> or an unrecognized value,
        /// <see cref="global::System.StringComparer.Ordinal"/> is used.
        /// </param>
        /// <returns><see langword="true"/> if both strings are equal; otherwise, <see langword="false"/>.</returns>
        /// <remarks>
        /// Reference equality (including two <see langword="null"/> values) short circuits to <see langword="true"/>,
        /// a single <see langword="null"/> short circuits to <see langword="false"/>, and differing lengths
        /// short circuit to <see langword="false"/> before any culture aware comparison is performed.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        internal static bool StringEquals(string? left, string? right, global::System.StringComparison? comparison = null)
        {
            if (global::System.Object.ReferenceEquals(left, right))
                return true;

            if (left is null || right is null)
                return false;

            if (left.Length != right.Length)
                return false;

            return comparison switch
            {
                global::System.StringComparison.Ordinal => global::System.StringComparer.Ordinal.Equals(left, right),
                global::System.StringComparison.OrdinalIgnoreCase => global::System.StringComparer.OrdinalIgnoreCase.Equals(left, right),
                global::System.StringComparison.CurrentCulture => global::System.StringComparer.CurrentCulture.Equals(left, right),
                global::System.StringComparison.CurrentCultureIgnoreCase => global::System.StringComparer.CurrentCultureIgnoreCase.Equals(left, right),
                global::System.StringComparison.InvariantCulture => global::System.StringComparer.InvariantCulture.Equals(left, right),
                global::System.StringComparison.InvariantCultureIgnoreCase => global::System.StringComparer.InvariantCultureIgnoreCase.Equals(left, right),
                _ => global::System.StringComparer.Ordinal.Equals(left, right),
            };
        }


        /// <summary>
        /// Computes a hash code for a sequence using the default comparer for <typeparamref name="T"/>.
        /// </summary>
        /// <typeparam name="T">The type of the elements in the sequence.</typeparam>
        /// <param name="items">The sequence to hash.</param>
        /// <returns>A hash code for the sequence, or <c>0</c> when <paramref name="items"/> is <see langword="null"/>.</returns>
        /// <remarks>
        /// The hash code is order dependent because each element is folded in with the rolling prime multiplier.
        /// <see langword="null"/> elements contribute <c>0</c>.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        internal static int SequenceHashCode<T>(global::System.Collections.Generic.IEnumerable<T>? items)
        {
            if (items is null)
                return 0;

            int hashCode = HashSeed;

            var valueComparer = global::System.Collections.Generic.EqualityComparer<T>.Default;
            foreach (var item in items)
                hashCode = (hashCode * Multiplier) + (item is null ? 0 : valueComparer.GetHashCode(item));

            return hashCode;
        }

        /// <summary>
        /// Computes an order-independent hash code for a dictionary.
        /// </summary>
        /// <typeparam name="TKey">The type of the keys in the dictionary.</typeparam>
        /// <typeparam name="TValue">The type of the values in the dictionary.</typeparam>
        /// <param name="items">The dictionary to hash.</param>
        /// <returns>A hash code for the dictionary, or <c>0</c> when <paramref name="items"/> is <see langword="null"/>.</returns>
        /// <remarks>
        /// Each key and value hash is combined with XOR, which is commutative and associative, so the enumeration order
        /// of the dictionary does not affect the result. <see langword="null"/> keys and values contribute <c>0</c>.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        internal static int DictionaryHashCode<TKey, TValue>(global::System.Collections.Generic.IDictionary<TKey, TValue>? items)
        {
            if (items is null)
                return 0;

            int hashCode = HashSeed;

            var keyComparer = global::System.Collections.Generic.EqualityComparer<TKey>.Default;
            var valueComparer = global::System.Collections.Generic.EqualityComparer<TValue>.Default;

            // XOR is commutative and associative so order of iteration doesn't matter
            foreach (var item in items)
            {
                int keyHash = item.Key is null ? 0 : keyComparer.GetHashCode(item.Key);
                int valueHash = item.Value is null ? 0 : valueComparer.GetHashCode(item.Value);

                hashCode ^= keyHash ^ valueHash;
            }

            return hashCode;
        }

        /// <summary>
        /// Computes an order-independent hash code for a set.
        /// </summary>
        /// <typeparam name="T">The type of the elements in the set.</typeparam>
        /// <param name="items">The set or sequence to hash.</param>
        /// <returns>A hash code for the set, or <c>0</c> when <paramref name="items"/> is <see langword="null"/>.</returns>
        /// <remarks>
        /// Each element hash is combined with XOR, which is commutative and associative, so the enumeration order of the
        /// sequence does not affect the result. <see langword="null"/> elements contribute <c>0</c>.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        internal static int HashSetHashCode<T>(global::System.Collections.Generic.IEnumerable<T>? items)
        {
            if (items is null)
                return 0;

            int hashCode = HashSeed;

            var valueComparer = global::System.Collections.Generic.EqualityComparer<T>.Default;

            // XOR is commutative and associative so order of iteration doesn't matter
            foreach (var item in items)
                hashCode ^= item is null ? 0 : valueComparer.GetHashCode(item);

            return hashCode;
        }

        /// <summary>
        /// Computes a hash code for a string using the specified <see cref="global::System.StringComparison"/>.
        /// </summary>
        /// <param name="value">The string to hash.</param>
        /// <param name="comparison">
        /// The comparison rules to use. When <see langword="null"/> or an unrecognized value,
        /// <see cref="global::System.StringComparer.Ordinal"/> is used.
        /// </param>
        /// <returns>
        /// A hash code for the string, or <see cref="NullValue"/> when <paramref name="value"/> is
        /// <see langword="null"/> so it doesn't collide with the hash code of an empty string.
        /// </returns>
        [global::System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        internal static int StringHashCode(string? value, global::System.StringComparison? comparison = null)
        {
            if (value is null)
                return NullValue;

            return comparison switch
            {
                global::System.StringComparison.Ordinal => global::System.StringComparer.Ordinal.GetHashCode(value),
                global::System.StringComparison.OrdinalIgnoreCase => global::System.StringComparer.OrdinalIgnoreCase.GetHashCode(value),
                global::System.StringComparison.CurrentCulture => global::System.StringComparer.CurrentCulture.GetHashCode(value),
                global::System.StringComparison.CurrentCultureIgnoreCase => global::System.StringComparer.CurrentCultureIgnoreCase.GetHashCode(value),
                global::System.StringComparison.InvariantCulture => global::System.StringComparer.InvariantCulture.GetHashCode(value),
                global::System.StringComparison.InvariantCultureIgnoreCase => global::System.StringComparer.InvariantCultureIgnoreCase.GetHashCode(value),
                _ => global::System.StringComparer.Ordinal.GetHashCode(value),
            };
        }


        /// <summary>
        /// Attempts to get the number of elements in a sequence without enumerating it.
        /// </summary>
        /// <typeparam name="T">The type of the elements in the sequence.</typeparam>
        /// <param name="source">The sequence to get the count for.</param>
        /// <param name="count">
        /// When this method returns <see langword="true"/>, contains the number of elements in the sequence;
        /// otherwise, zero.
        /// </param>
        /// <returns>
        /// <see langword="true"/> when the sequence implements <see cref="global::System.Collections.Generic.ICollection{T}"/>
        /// or <see cref="global::System.Collections.Generic.IReadOnlyCollection{T}"/> and the count could be read;
        /// otherwise, <see langword="false"/>.
        /// </returns>
        private static bool TryGetCount<T>(global::System.Collections.Generic.IEnumerable<T> source, out int count)
        {
            switch (source)
            {
                case global::System.Collections.Generic.ICollection<T> collection:
                    count = collection.Count;
                    return true;
                case global::System.Collections.Generic.IReadOnlyCollection<T> readOnlyCollection:
                    count = readOnlyCollection.Count;
                    return true;
                default:
                    count = 0;
                    return false;
            }
        }
    }
}
