using Equatable.SourceGenerator.Models;

using Microsoft.CodeAnalysis;

namespace Equatable.SourceGenerator;

public static class EquatableWriter
{
    public static string Generate(EquatableClass entityClass)
    {
        if (entityClass is null)
            throw new ArgumentNullException(nameof(entityClass));

        var codeBuilder = new IndentedStringBuilder();
        codeBuilder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        codeBuilder
            .Append("namespace ")
            .AppendLine(entityClass.EntityNamespace)
            .AppendLine("{")
            .IncrementIndent();

        // support nested types
        foreach (var containingClass in entityClass.ContainingTypes)
        {
            codeBuilder
                .Append("partial ")
                .AppendIf("record ", containingClass.IsRecord)
                .AppendIf("class ", !containingClass.IsValueType)
                .AppendIf("struct ", containingClass.IsValueType)
                .AppendLine(containingClass.EntityName)
                .AppendLine("{")
                .IncrementIndent();
        }

        codeBuilder
            .Append("partial ")
            .AppendIf("record ", entityClass.IsRecord)
            .AppendIf("class ", !entityClass.IsValueType)
            .AppendIf("struct ", entityClass.IsValueType)
            .Append(entityClass.EntityName);

        if (!entityClass.IsRecord)
        {
            codeBuilder
                .Append(" : global::System.IEquatable<")
                .Append(entityClass.FullyQualified)
                .AppendIf("?", !entityClass.IsValueType)
                .Append(">");
        }

        codeBuilder
            .AppendLine()
            .AppendLine("{")
            .IncrementIndent();

        GenerateEquatable(codeBuilder, entityClass);
        GenerateEquals(codeBuilder, entityClass);
        GenerateHashCode(codeBuilder, entityClass);

        codeBuilder
            .DecrementIndent()
            .AppendLine("}"); // class

        // support nested types
        foreach (var containingClass in entityClass.ContainingTypes)
        {
            codeBuilder
                .DecrementIndent()
                .AppendLine("}");
        }

        codeBuilder
            .DecrementIndent()
            .AppendLine("}"); // namespace

        return codeBuilder.ToString();
    }

    private static void GenerateEquatable(IndentedStringBuilder codeBuilder, EquatableClass entityClass)
    {
        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .Append("public ")
            .AppendIf("virtual ", entityClass.IsRecord && !entityClass.IsSealed)
            .Append("bool Equals(")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .AppendLine(" other)")
            .AppendLine("{")
            .IncrementIndent();

        bool wrote;
        if (entityClass.IsValueType)
        {
            codeBuilder.Append("return");
            wrote = false;
        }
        else
        {
            codeBuilder.Append("return !(other is null)");
            wrote = true;
        }

        if (entityClass.IncludeBaseEqualsMethod)
        {
            codeBuilder
                .AppendLineIf(wrote)
                .AppendIf("    &&", wrote)
                .Append(" base.Equals(other)");

            wrote = true;
        }

        foreach (var entityProperty in entityClass.Properties)
        {
            codeBuilder
                .AppendLineIf(wrote)
                .AppendIf("    &&", wrote);

            switch (entityProperty.ComparerType)
            {
                case ComparerTypes.Dictionary:
                    codeBuilder
                        .Append(" DictionaryEquals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.HashSet:
                    codeBuilder
                        .Append(" HashSetEquals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.Reference:
                    codeBuilder
                        .Append(" global::System.Object.ReferenceEquals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.Sequence:
                    codeBuilder
                        .Append(" SequenceEquals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.String:
                    codeBuilder
                        .Append(" global::System.StringComparer.")
                        .Append(entityProperty.ComparerName)
                        .Append(".Equals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.Custom:
                    codeBuilder
                        .Append(" ")
                        .Append(entityProperty.ComparerName)
                        .Append(".")
                        .Append(entityProperty.ComparerInstance ?? "Default")
                        .Append(".Equals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                default:
                    codeBuilder
                        .Append(" global::System.Collections.Generic.EqualityComparer<")
                        .Append(entityProperty.PropertyType)
                        .Append(">.Default.Equals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
            }

            wrote = true;
        }

        codeBuilder
            .AppendLine(";")
            .AppendLine();

        GenerateEquatableFunctions(codeBuilder, entityClass);

        codeBuilder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    private static void GenerateEquatableFunctions(IndentedStringBuilder codeBuilder, EquatableClass entityClass)
    {
        if (entityClass is null)
            return;

        if (entityClass.Properties.Any(p => p.ComparerType == ComparerTypes.Dictionary))
        {
            codeBuilder
                .AppendLine("static bool DictionaryEquals<TKey, TValue>(global::System.Collections.Generic.IDictionary<TKey, TValue>? left, global::System.Collections.Generic.IDictionary<TKey, TValue>? right)")
                .AppendLine("{")
                .IncrementIndent()
                .AppendLine("if (global::System.Object.ReferenceEquals(left, right))")
                .AppendLine("    return true;")
                .AppendLine()
                .AppendLine("if (left is null || right is null)")
                .AppendLine("    return false;")
                .AppendLine()
                .AppendLine("if (left.Count != right.Count)")
                .AppendLine("    return false;")
                .AppendLine();

            codeBuilder
                .AppendLine("foreach (var pair in left)")
                .AppendLine("{")
                .IncrementIndent()
                .AppendLine("if (!right.TryGetValue(pair.Key, out var value))")
                .AppendLine("    return false;")
                .AppendLine()
                .AppendLine("if (!global::System.Collections.Generic.EqualityComparer<TValue>.Default.Equals(pair.Value, value))")
                .AppendLine("    return false;")
                .AppendLine()
                .DecrementIndent()
                .AppendLine("}"); // foreach

            codeBuilder
                .AppendLine()
                .AppendLine("return true;")
                .DecrementIndent()
                .AppendLine("}")
                .AppendLine();
        }

        if (entityClass.Properties.Any(p => p.ComparerType == ComparerTypes.HashSet))
        {
            codeBuilder
                .AppendLine("static bool HashSetEquals<T>(global::System.Collections.Generic.IEnumerable<T>? left, global::System.Collections.Generic.IEnumerable<T>? right)")
                .AppendLine("{")
                .IncrementIndent()
                .AppendLine("if (global::System.Object.ReferenceEquals(left, right))")
                .AppendLine("    return true;")
                .AppendLine()
                .AppendLine("if (left is null || right is null)")
                .AppendLine("    return false;")
                .AppendLine()
                .AppendLine("if (left is global::System.Collections.Generic.ISet<T> leftSet)")
                .AppendLine("    return leftSet.SetEquals(right);")
                .AppendLine()
                .AppendLine("if (right is global::System.Collections.Generic.ISet<T> rightSet)")
                .AppendLine("    return rightSet.SetEquals(left);")
                .AppendLine()
                .AppendLine("var hashSet = new global::System.Collections.Generic.HashSet<T>(left, global::System.Collections.Generic.EqualityComparer<T>.Default);")
                .AppendLine("return hashSet.SetEquals(right);")
                .DecrementIndent()
                .AppendLine("}")
                .AppendLine();
        }

        if (entityClass.Properties.Any(p => p.ComparerType == ComparerTypes.Sequence))
        {
            codeBuilder
                .AppendLine("static bool SequenceEquals<T>(global::System.Collections.Generic.IEnumerable<T>? left, global::System.Collections.Generic.IEnumerable<T>? right)")
                .AppendLine("{")
                .IncrementIndent()
                .AppendLine("if (global::System.Object.ReferenceEquals(left, right))")
                .AppendLine("    return true;")
                .AppendLine()
                .AppendLine("if (left is null || right is null)")
                .AppendLine("    return false;")
                .AppendLine()
                .AppendLine("return global::System.Linq.Enumerable.SequenceEqual(left, right, global::System.Collections.Generic.EqualityComparer<T>.Default);")
                .DecrementIndent()
                .AppendLine("}")
                .AppendLine();
        }
    }

    private static void GenerateEquals(IndentedStringBuilder codeBuilder, EquatableClass entityClass)
    {
        // can't override equal for record types
        if (entityClass.IsRecord)
            return;

        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .AppendLine("public override bool Equals(object? obj)")
            .AppendLine("{")
            .IncrementIndent();

        if (entityClass.IsValueType)
        {
            codeBuilder
                .Append("return obj is ")
                .Append(entityClass.FullyQualified)
                .AppendLine(" instance && Equals(instance);");
        }
        else
        {
            codeBuilder
                .Append("return Equals(obj as ")
                .Append(entityClass.FullyQualified)
                .AppendLine(");");
        }

        codeBuilder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();

        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .Append("public static bool operator ==(")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .Append(" left, ")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .AppendLine(" right)")
            .AppendLine("{")
            .IncrementIndent()
            .Append("return global::System.Collections.Generic.EqualityComparer<")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .AppendLine(">.Default.Equals(left, right);")
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();

        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .Append("public static bool operator !=(")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .Append(" left, ")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .AppendLine(" right)")
            .AppendLine("{")
            .IncrementIndent()
            .AppendLine("return !(left == right);")
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    private static void GenerateHashCode(IndentedStringBuilder codeBuilder, EquatableClass entityClass)
    {
        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .Append("public override int GetHashCode()")
            .AppendLine("{")
            .IncrementIndent();

        codeBuilder
            .Append("int hashCode = ")
            .Append(entityClass.SeedHash)
            .AppendLine(";");

        if (entityClass.IncludeBaseHashMethod)
            codeBuilder.AppendLine("hashCode = (hashCode * -1521134295) + base.GetHashCode();");

        foreach (var entityProperty in entityClass.Properties)
        {
            switch (entityProperty.ComparerType)
            {
                case ComparerTypes.Dictionary:
                    codeBuilder
                        .Append("hashCode = (hashCode * -1521134295) + ")
                        .Append("DictionaryHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine(");");
                    break;
                case ComparerTypes.HashSet:
                    codeBuilder
                        .Append("hashCode = (hashCode * -1521134295) + ")
                        .Append("HashSetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine(");");
                    break;
                case ComparerTypes.Reference:
                    codeBuilder
                        .Append("hashCode = (hashCode * -1521134295) + ")
                        .Append("global::System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine("!);");
                    break;
                case ComparerTypes.Sequence:
                    codeBuilder
                        .Append("hashCode = (hashCode * -1521134295) + ")
                        .Append("SequenceHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine(");");
                    break;
                case ComparerTypes.String:
                    codeBuilder
                        .Append("hashCode = (hashCode * -1521134295) + ")
                        .Append("global::System.StringComparer.")
                        .Append(entityProperty.ComparerName)
                        .Append(".GetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine("!);");
                    break;
                case ComparerTypes.Custom:
                    codeBuilder
                        .Append("hashCode = (hashCode * -1521134295) + ")
                        .Append(entityProperty.ComparerName)
                        .Append(".")
                        .Append(entityProperty.ComparerInstance ?? "Default")
                        .Append(".GetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine("!);");
                    break;
                default:
                    codeBuilder
                        .Append("hashCode = (hashCode * -1521134295) + ")
                        .Append("global::System.Collections.Generic.EqualityComparer<")
                        .Append(entityProperty.PropertyType)
                        .Append(">.Default.GetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine("!);");
                    break;
            }
        }

        codeBuilder
            .AppendLine("return hashCode;")
            .AppendLine();

        GenerateHashCodeFunctions(codeBuilder, entityClass);

        codeBuilder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    private static void GenerateHashCodeFunctions(IndentedStringBuilder codeBuilder, EquatableClass entityClass)
    {
        if (entityClass is null)
            return;

        if (entityClass.Properties.Any(p => p.ComparerType == ComparerTypes.Dictionary))
        {
            codeBuilder
                .AppendLine("static int DictionaryHashCode<TKey, TValue>(global::System.Collections.Generic.IDictionary<TKey, TValue>? items)")
                .AppendLine("{")
                .IncrementIndent()
                .AppendLine("if (items is null)")
                .AppendLine("    return 0;")
                .AppendLine();

            codeBuilder
                .Append("int hashCode = ")
                .Append(entityClass.SeedHash)
                .AppendLine(";")
                .AppendLine()
                .AppendLine("// sort by key to ensure dictionary with different order are the same")
                .AppendLine("foreach (var item in global::System.Linq.Enumerable.OrderBy(items, d => d.Key))")
                .AppendLine("{")
                .IncrementIndent()
                .AppendLine("hashCode = (hashCode * -1521134295) + global::System.Collections.Generic.EqualityComparer<TKey>.Default.GetHashCode(item.Key!);")
                .AppendLine("hashCode = (hashCode * -1521134295) + global::System.Collections.Generic.EqualityComparer<TValue>.Default.GetHashCode(item.Value!);")
                .DecrementIndent()
                .AppendLine("}"); // foreach

            codeBuilder
                .AppendLine()
                .AppendLine("return hashCode;")
                .DecrementIndent()
                .AppendLine("}")
                .AppendLine();
        }

        if (entityClass.Properties.Any(p => p.ComparerType == ComparerTypes.HashSet))
        {
            codeBuilder
                .AppendLine("static int HashSetHashCode<T>(global::System.Collections.Generic.IEnumerable<T>? items)")
                .AppendLine("{")
                .IncrementIndent()
                .AppendLine("if (items is null)")
                .AppendLine("    return 0;")
                .AppendLine()
                .Append("int hashCode = ")
                .Append(entityClass.SeedHash)
                .AppendLine(";")
                .AppendLine()
                .AppendLine("// sort to ensure set with different order are the same")
                .AppendLine("foreach (var item in global::System.Linq.Enumerable.OrderBy(items, d => d))")
                .AppendLine("    hashCode = (hashCode * -1521134295) + global::System.Collections.Generic.EqualityComparer<T>.Default.GetHashCode(item!);")
                .AppendLine()
                .AppendLine("return hashCode;")
                .DecrementIndent()
                .AppendLine("}")
                .AppendLine();
        }

        if (entityClass.Properties.Any(p => p.ComparerType == ComparerTypes.Sequence))
        {
            codeBuilder
                .AppendLine("static int SequenceHashCode<T>(global::System.Collections.Generic.IEnumerable<T>? items)")
                .AppendLine("{")
                .IncrementIndent()
                .AppendLine("if (items is null)")
                .AppendLine("    return 0;")
                .AppendLine()
                .Append("int hashCode = ")
                .Append(entityClass.SeedHash)
                .AppendLine(";")
                .AppendLine()
                .AppendLine("foreach (var item in items)")
                .AppendLine("    hashCode = (hashCode * -1521134295) + global::System.Collections.Generic.EqualityComparer<T>.Default.GetHashCode(item!);")
                .AppendLine()
                .AppendLine("return hashCode;")
                .DecrementIndent()
                .AppendLine("}")
                .AppendLine();
        }
    }
}
