<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IsPackable>true</IsPackable>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <AnalyzerLanguage>cs</AnalyzerLanguage>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
  </ItemGroup>

  <ItemGroup>
    <!-- https://learn.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support -->
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Equatable.Shared\Attributes.cs" LogicalName="Equatable.Generator.Embedded.Attributes.cs" />
    <EmbeddedResource Include="..\Equatable.Shared\Comparer.cs" LogicalName="Equatable.Generator.Embedded.Comparer.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" PackagePath="analyzers/dotnet/cs" Pack="true" Visible="false" />
    <None Include="Equatable.Generator.targets" PackagePath="build/$(PackageId).targets" Pack="true" Visible="true" />
  </ItemGroup>

</Project>
