using Equatable.Generator.Infrastructure;
using Equatable.Generator.Models;

using Microsoft.CodeAnalysis;

namespace Equatable.Generator;

public static class EquatableWriter
{
    public static string Generate(EquatableClass entityClass)
    {
        if (entityClass is null)
            throw new ArgumentNullException(nameof(entityClass));

        var codeBuilder = new IndentedStringBuilder();
        codeBuilder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        codeBuilder
            .Append("namespace ")
            .AppendLine(entityClass.EntityNamespace)
            .AppendLine("{")
            .IncrementIndent();

        // support nested types
        foreach (var containingClass in entityClass.ContainingTypes)
        {
            codeBuilder
                .Append("partial ")
                .AppendIf("record ", containingClass.IsRecord)
                .AppendIf("class ", !containingClass.IsValueType)
                .AppendIf("struct ", containingClass.IsValueType)
                .AppendLine(containingClass.EntityName)
                .AppendLine("{")
                .IncrementIndent();
        }

        codeBuilder
            .Append("partial ")
            .AppendIf("record ", entityClass.IsRecord)
            .AppendIf("class ", !entityClass.IsValueType)
            .AppendIf("struct ", entityClass.IsValueType)
            .Append(entityClass.EntityName);

        if (!entityClass.IsRecord)
        {
            codeBuilder
                .Append(" : global::System.IEquatable<")
                .Append(entityClass.FullyQualified)
                .AppendIf("?", !entityClass.IsValueType)
                .Append(">");
        }

        codeBuilder
            .AppendLine()
            .AppendLine("{")
            .IncrementIndent();

        GenerateEquatable(codeBuilder, entityClass);
        GenerateEquals(codeBuilder, entityClass);
        GenerateHashCode(codeBuilder, entityClass);

        codeBuilder
            .DecrementIndent()
            .AppendLine("}"); // class

        // support nested types
        foreach (var _ in entityClass.ContainingTypes)
        {
            codeBuilder
                .DecrementIndent()
                .AppendLine("}");
        }

        codeBuilder
            .DecrementIndent()
            .AppendLine("}"); // namespace

        return codeBuilder.ToString();
    }

    private static void GenerateEquatable(IndentedStringBuilder codeBuilder, EquatableClass entityClass)
    {
        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .Append("public ")
            .AppendIf("virtual ", entityClass.IsRecord && !entityClass.IsSealed)
            .Append("bool Equals(")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .AppendLine(" other)")
            .AppendLine("{")
            .IncrementIndent();

        bool wrote;
        if (entityClass.IsValueType)
        {
            codeBuilder.Append("return");
            wrote = false;
        }
        else
        {
            codeBuilder.Append("return !(other is null)");
            wrote = true;
        }

        if (entityClass.IncludeBaseEqualsMethod)
        {
            codeBuilder
                .AppendLineIf(wrote)
                .AppendIf("    &&", wrote)
                .Append(" base.Equals(other)");

            wrote = true;
        }

        foreach (var entityProperty in entityClass.Properties)
        {
            codeBuilder
                .AppendLineIf(wrote)
                .AppendIf("    &&", wrote);

            switch (entityProperty.ComparerType)
            {
                case ComparerTypes.Dictionary:
                    codeBuilder
                        .Append(" global::Equatable.Comparer.DictionaryEquals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.HashSet:
                    codeBuilder
                        .Append(" global::Equatable.Comparer.HashSetEquals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.Reference:
                    codeBuilder
                        .Append(" global::System.Object.ReferenceEquals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.Sequence:
                    codeBuilder
                        .Append(" global::Equatable.Comparer.SequenceEquals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.String:
                    codeBuilder
                        .Append(" global::System.StringComparer.")
                        .Append(entityProperty.ComparerName)
                        .Append(".Equals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.Custom:
                    codeBuilder
                        .Append(" ")
                        .Append(entityProperty.ComparerName)
                        .Append(".")
                        .Append(entityProperty.ComparerInstance ?? "Default")
                        .Append(".Equals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
                case ComparerTypes.ValueType:
                    codeBuilder
                        .Append(" ")
                        .Append(entityProperty.PropertyName)
                        .Append(" == other.")
                        .Append(entityProperty.PropertyName);

                    break;
                default:
                    codeBuilder
                        .Append(" global::System.Collections.Generic.EqualityComparer<")
                        .Append(entityProperty.PropertyType)
                        .Append(">.Default.Equals(")
                        .Append(entityProperty.PropertyName)
                        .Append(", other.")
                        .Append(entityProperty.PropertyName)
                        .Append(")");

                    break;
            }

            wrote = true;
        }

        codeBuilder
            .AppendLine(";");

        codeBuilder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    private static void GenerateEquals(IndentedStringBuilder codeBuilder, EquatableClass entityClass)
    {
        // can't override equal for record types
        if (entityClass.IsRecord)
            return;

        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .AppendLine("public override bool Equals(object? obj)")
            .AppendLine("{")
            .IncrementIndent();

        if (entityClass.IsValueType)
        {
            codeBuilder
                .Append("return obj is ")
                .Append(entityClass.FullyQualified)
                .AppendLine(" instance && Equals(instance);");
        }
        else
        {
            codeBuilder
                .Append("return Equals(obj as ")
                .Append(entityClass.FullyQualified)
                .AppendLine(");");
        }

        codeBuilder
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();

        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .Append("public static bool operator ==(")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .Append(" left, ")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .AppendLine(" right)")
            .AppendLine("{")
            .IncrementIndent()
            .Append("return global::System.Collections.Generic.EqualityComparer<")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .AppendLine(">.Default.Equals(left, right);")
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();

        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .Append("public static bool operator !=(")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .Append(" left, ")
            .Append(entityClass.FullyQualified)
            .AppendIf("?", !entityClass.IsValueType)
            .AppendLine(" right)")
            .AppendLine("{")
            .IncrementIndent()
            .AppendLine("return !(left == right);")
            .DecrementIndent()
            .AppendLine("}")
            .AppendLine();
    }

    private static void GenerateHashCode(IndentedStringBuilder codeBuilder, EquatableClass entityClass)
    {
        codeBuilder
            .AppendLine("/// <inheritdoc />")
            .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
            .Append(ThisAssembly.Product)
            .Append("\", \"")
            .Append(ThisAssembly.InformationalVersion)
            .AppendLine("\")]")
            .AppendLine("public override int GetHashCode()")
            .AppendLine("{")
            .IncrementIndent();

        codeBuilder
            .AppendLine("int hashCode = global::Equatable.Comparer.HashSeed;");

        if (entityClass.IncludeBaseHashMethod)
            codeBuilder.AppendLine("hashCode = (hashCode * global::Equatable.Comparer.HashMultiplier) + base.GetHashCode();");

        foreach (var entityProperty in entityClass.Properties)
        {
            switch (entityProperty.ComparerType)
            {
                case ComparerTypes.Dictionary:
                    codeBuilder
                        .Append("hashCode = (hashCode * global::Equatable.Comparer.HashMultiplier) + ")
                        .Append("global::Equatable.Comparer.DictionaryHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine(");");
                    break;
                case ComparerTypes.HashSet:
                    codeBuilder
                        .Append("hashCode = (hashCode * global::Equatable.Comparer.HashMultiplier) + ")
                        .Append("global::Equatable.Comparer.HashSetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine(");");
                    break;
                case ComparerTypes.Reference:
                    codeBuilder
                        .Append("hashCode = (hashCode * global::Equatable.Comparer.HashMultiplier) + ")
                        .Append("global::System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine("!);");
                    break;
                case ComparerTypes.Sequence:
                    codeBuilder
                        .Append("hashCode = (hashCode * global::Equatable.Comparer.HashMultiplier) + ")
                        .Append("global::Equatable.Comparer.SequenceHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine(");");
                    break;
                case ComparerTypes.String:
                    codeBuilder
                        .Append("hashCode = (hashCode * global::Equatable.Comparer.HashMultiplier) + ")
                        .Append("global::System.StringComparer.")
                        .Append(entityProperty.ComparerName)
                        .Append(".GetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine("!);");
                    break;
                case ComparerTypes.Custom:
                    codeBuilder
                        .Append("hashCode = (hashCode * global::Equatable.Comparer.HashMultiplier) + ")
                        .Append(entityProperty.ComparerName)
                        .Append(".")
                        .Append(entityProperty.ComparerInstance ?? "Default")
                        .Append(".GetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine("!);");
                    break;
                case ComparerTypes.ValueType:
                    codeBuilder
                        .Append("hashCode = (hashCode * global::Equatable.Comparer.HashMultiplier) + ")
                        .Append(entityProperty.PropertyName)
                        .AppendLine(".GetHashCode();");
                    break;
                default:
                    codeBuilder
                        .Append("hashCode = (hashCode * global::Equatable.Comparer.HashMultiplier) + ")
                        .Append("global::System.Collections.Generic.EqualityComparer<")
                        .Append(entityProperty.PropertyType)
                        .Append(">.Default.GetHashCode(")
                        .Append(entityProperty.PropertyName)
                        .AppendLine("!);");
                    break;
            }
        }

        codeBuilder
            .AppendLine("return hashCode;");

        codeBuilder
            .DecrementIndent()
            .AppendLine("}");
    }
}
